# Generated by Django 5.1.4 on 2025-01-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0002_profile_firstname_profile_lastname_profile_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mail',
            new_name='email',
        ),
    ]
