# Generated by Django 5.1.4 on 2025-01-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_rename_mail_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
