# Generated by Django 5.1.4 on 2025-01-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0004_rename_firstname_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
